# Generated by Django 3.1.4 on 2020-12-21 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('street_address', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(default='CA', max_length=3)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('\\d{2}-\\d{4}')], verbose_name='Team ID')),
                ('unique_id', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('[A-z0-9]{4}(?:-[A-z0-9]{4}){3}')], verbose_name='Unique ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teams.coach', verbose_name='Coach')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teams.school', verbose_name='School'),
        ),
    ]
