# Generated by Django 3.1.4 on 2020-12-22 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('\\d{2}-\\d{4}')], verbose_name='Team ID'),
        ),
    ]
