# Generated by Django 3.1.4 on 2020-12-23 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201222_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='unique_id',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('[A-z0-9]{4}(?:-[A-z0-9]{4}){2}')], verbose_name='Unique ID'),
        ),
    ]
