# Generated by Django 3.1.4 on 2020-12-21 06:12

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scores_csv', models.FileField(upload_to='')),
                ('individual_challenges', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
