# Generated by Django 3.1.4 on 2020-12-21 06:20

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cisco_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('individual_scores', jsonfield.fields.JSONField(blank=True, null=True)),
                ('total_rank', models.IntegerField()),
                ('state_rank', models.IntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
            ],
        ),
    ]
