# Generated by Django 3.1.4 on 2020-12-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201222_2313'),
        ('scores', '0002_teamscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamscore',
            unique_together={('team', 'round')},
        ),
    ]
