# Generated by Django 3.1.4 on 2020-12-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20201222_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='col_cisco',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='col_cum',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='col_division',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='col_image',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='col_state',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='col_team',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
