# Generated by Django 3.1.4 on 2020-12-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20201223_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscore',
            name='total_rank',
        ),
        migrations.AddField(
            model_name='teamscore',
            name='division_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='cisco_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='cumulative_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='image_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='state_rank',
            field=models.IntegerField(null=True),
        ),
    ]
